// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnnpEn1eUroqzh3--cD3f6WUlsCkW6ajw',
    appId: '1:272489690947:android:4ea65fa108e9384e5961f6',
    messagingSenderId: '272489690947',
    projectId: 'newhorizontrav-58086',
    storageBucket: 'newhorizontrav-58086.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPcqZ2qa4qsHcUCIuVDzmfJwcb9-reGiA',
    appId: '1:272489690947:ios:819af37fba6ee1055961f6',
    messagingSenderId: '272489690947',
    projectId: 'newhorizontrav-58086',
    storageBucket: 'newhorizontrav-58086.firebasestorage.app',
    androidClientId: '272489690947-ph0o0s0aq5boficof23nkbnjg4j6j4nr.apps.googleusercontent.com',
    iosClientId: '272489690947-kmkn2elel80385m2gpmjnf7oq50c9c6v.apps.googleusercontent.com',
    iosBundleId: 'com.newhorizontrav.newhorizontrav',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN9_VPTLRnLtvoLc4HMqTOoJvr9YyXJHA',
    appId: '1:272489690947:web:c28dcbbfaa4529ea5961f6',
    messagingSenderId: '272489690947',
    projectId: 'newhorizontrav-58086',
    authDomain: 'newhorizontrav-58086.firebaseapp.com',
    storageBucket: 'newhorizontrav-58086.firebasestorage.app',
    measurementId: 'G-XX42Q17B3L',
  );

}