import 'package:newhorizontrav/model/airline_model.dart';

class AirlineRepo {
  List<Map<String, dynamic>> data = [
    {
      "id": 1,
      "code": "QR",
      "name": {"en": "Qatar Airways", "ar": "الخطوط الجوية القطرية"},
      "country_code": "qa",
      "image": "qr",
      "note": "We use cookies on our website",
    },
    {
      "id": 2,
      "code": "SV",
      "name": {"en": "Saudia", "ar": "الخطوط السعودية"},
      "country_code": "sa",
      "image": "sv",
      "note": null,
    },
    {
      "id": 3,
      "code": "EK",
      "name": {"en": "Emirates", "ar": "طيران الإمارات"},
      "country_code": "ae",
      "image": "ek",
      "note": null,
    },
    {
      "id": 4,
      "code": "EY",
      "name": {"en": "Etihad Airways", "ar": "الاتحاد للطيران"},
      "country_code": "ae",
      "image": "ey",
      "note": null,
    },
    {
      "id": 5,
      "code": "FZ",
      "name": {"en": "flydubai", "ar": "فلاي دبي"},
      "country_code": "ae",
      "image": "fz",
      "note": null,
    },
    {
      "id": 6,
      "code": "G9",
      "name": {"en": "Air Arabia", "ar": "العربية للطيران"},
      "country_code": "ae",
      "image": "g9",
      "note": null,
    },
    {
      "id": 7,
      "code": "WY",
      "name": {"en": "Oman Air", "ar": "الطيران العُماني"},
      "country_code": "om",
      "image": "wy",
      "note": null,
    },
    {
      "id": 8,
      "code": "KU",
      "name": {"en": "Kuwait Airways", "ar": "الخطوط الجوية الكويتية"},
      "country_code": "kw",
      "image": "ku",
      "note": null,
    },
    {
      "id": 9,
      "code": "GF",
      "name": {"en": "Gulf Air", "ar": "طيران الخليج"},
      "country_code": "bh",
      "image": "gf",
      "note": null,
    },
    {
      "id": 10,
      "code": "RJ",
      "name": {"en": "Royal Jordanian", "ar": "الملكية الأردنية"},
      "country_code": "jo",
      "image": "rj",
      "note": null,
    },
    {
      "id": 11,
      "code": "ME",
      "name": {"en": "Middle East Airlines", "ar": "طيران الشرق الأوسط"},
      "country_code": "lb",
      "image": "me",
      "note": null,
    },
    {
      "id": 12,
      "code": "XY",
      "name": {"en": "flynas", "ar": "طيران ناس"},
      "country_code": "sa",
      "image": "xy",
      "note": null,
    },
    {
      "id": 13,
      "code": "J9",
      "name": {"en": "Jazeera Airways", "ar": "طيران الجزيرة"},
      "country_code": "kw",
      "image": "j9",
      "note": null,
    },
    {
      "id": 14,
      "code": "NE",
      "name": {"en": "Nesma Airlines", "ar": "طيران نسما"},
      "country_code": "sa",
      "image": "ne",
      "note": null,
    },
    {
      "id": 15,
      "code": "3O",
      "name": {"en": "Air Arabia Maroc", "ar": "العربية للطيران المغرب"},
      "country_code": "ma",
      "image": "3o",
      "note": null,
    },
    {
      "id": 16,
      "code": "E5",
      "name": {"en": "Air Arabia Egypt", "ar": "العربية للطيران مصر"},
      "country_code": "eg",
      "image": "e5",
      "note": null,
    },
    {
      "id": 17,
      "code": "MS",
      "name": {"en": "EgyptAir", "ar": "مصر للطيران"},
      "country_code": "eg",
      "image": "ms",
      "note": null,
    },
    {
      "id": 18,
      "code": "TU",
      "name": {"en": "Tunisair", "ar": "الخطوط التونسية"},
      "country_code": "tn",
      "image": "tu",
      "note": null,
    },
    {
      "id": 19,
      "code": "BJ",
      "name": {"en": "Nouvelair", "ar": "طيران نوفيل إير"},
      "country_code": "tn",
      "image": "bj",
      "note": null,
    },
    {
      "id": 20,
      "code": "AH",
      "name": {"en": "Air Algérie", "ar": "الخطوط الجوية الجزائرية"},
      "country_code": "dz",
      "image": "ah",
      "note": null,
    },
    {
      "id": 21,
      "code": "AT",
      "name": {"en": "Royal Air Maroc", "ar": "الخطوط الملكية المغربية"},
      "country_code": "ma",
      "image": "at",
      "note": null,
    },
    {
      "id": 22,
      "code": "8U",
      "name": {"en": "Afriqiyah Airways", "ar": "الخطوط الأفريقية"},
      "country_code": "ly",
      "image": "8u",
      "note": null,
    },
    {
      "id": 23,
      "code": "LN",
      "name": {"en": "Libyan Airlines", "ar": "الخطوط الجوية الليبية"},
      "country_code": "ly",
      "image": "ln",
      "note": null,
    },
    {
      "id": 24,
      "code": "ET",
      "name": {"en": "Ethiopian Airlines", "ar": "الخطوط الجوية الإثيوبية"},
      "country_code": "et",
      "image": "et",
      "note": null,
    },
    {
      "id": 25,
      "code": "KQ",
      "name": {"en": "Kenya Airways", "ar": "الخطوط الجوية الكينية"},
      "country_code": "ke",
      "image": "kq",
      "note": null,
    },
    {
      "id": 26,
      "code": "PW",
      "name": {"en": "Precision Air", "ar": "طيران بريسيجن"},
      "country_code": "tz",
      "image": "pw",
      "note": null,
    },
    {
      "id": 27,
      "code": "WB",
      "name": {"en": "RwandAir", "ar": "طيران رواند إير"},
      "country_code": "rw",
      "image": "wb",
      "note": null,
    },
    {
      "id": 28,
      "code": "SA",
      "name": {"en": "South African Airways", "ar": "الخطوط الجوية الجنوب أفريقية"},
      "country_code": "za",
      "image": "sa",
      "note": null,
    },
    {
      "id": 29,
      "code": "FA",
      "name": {"en": "FlySafair", "ar": "فلاي سافير"},
      "country_code": "za",
      "image": "fa",
      "note": null,
    },
    {
      "id": 30,
      "code": "4Z",
      "name": {"en": "Airlink", "ar": "طيران إيرلينك"},
      "country_code": "za",
      "image": "4z",
      "note": null,
    },
    {
      "id": 31,
      "code": "DT",
      "name": {"en": "TAAG Angola Airlines", "ar": "طيران طاغ أنغولا"},
      "country_code": "ao",
      "image": "dt",
      "note": null,
    },
    {
      "id": 32,
      "code": "TM",
      "name": {"en": "LAM Mozambique Airlines", "ar": "الخطوط الجوية الموزمبيقية لام"},
      "country_code": "mz",
      "image": "tm",
      "note": null,
    },
    {
      "id": 33,
      "code": "HM",
      "name": {"en": "Air Seychelles", "ar": "طيران سيشل"},
      "country_code": "sc",
      "image": "hm",
      "note": null,
    },
    {
      "id": 34,
      "code": "MK",
      "name": {"en": "Air Mauritius", "ar": "طيران موريشيوس"},
      "country_code": "mu",
      "image": "mk",
      "note": null,
    },
    {
      "id": 35,
      "code": "IR",
      "name": {"en": "Iran Air", "ar": "إيران إير"},
      "country_code": "ir",
      "image": "ir",
      "note": null,
    },
    {
      "id": 36,
      "code": "W5",
      "name": {"en": "Mahan Air", "ar": "ماهان إير"},
      "country_code": "ir",
      "image": "w5",
      "note": null,
    },
    {
      "id": 37,
      "code": "IA",
      "name": {"en": "Iraqi Airways", "ar": "الخطوط الجوية العراقية"},
      "country_code": "iq",
      "image": "ia",
      "note": null,
    },
    {
      "id": 38,
      "code": "RQ",
      "name": {"en": "Kam Air", "ar": "كام إير"},
      "country_code": "af",
      "image": "rq",
      "note": null,
    },
    {
      "id": 39,
      "code": "HY",
      "name": {"en": "Uzbekistan Airways", "ar": "الخطوط الجوية الأوزبكية"},
      "country_code": "uz",
      "image": "hy",
      "note": null,
    },
    {
      "id": 40,
      "code": "KC",
      "name": {"en": "Air Astana", "ar": "طيران أستانا"},
      "country_code": "kz",
      "image": "kc",
      "note": null,
    },
    {
      "id": 41,
      "code": "DV",
      "name": {"en": "SCAT Airlines", "ar": "طيران سكات"},
      "country_code": "kz",
      "image": "dv",
      "note": null,
    },
    {
      "id": 42,
      "code": "SU",
      "name": {"en": "Aeroflot", "ar": "آيروفلوت"},
      "country_code": "ru",
      "image": "su",
      "note": null,
    },
    {
      "id": 43,
      "code": "S7",
      "name": {"en": "S7 Airlines", "ar": "طيران إس7"},
      "country_code": "ru",
      "image": "s7",
      "note": null,
    },
    {
      "id": 44,
      "code": "U6",
      "name": {"en": "Ural Airlines", "ar": "خطوط يورال الجوية"},
      "country_code": "ru",
      "image": "u6",
      "note": null,
    },
    {
      "id": 45,
      "code": "DP",
      "name": {"en": "Pobeda", "ar": "بوبييدا"},
      "country_code": "ru",
      "image": "dp",
      "note": null,
    },
    {
      "id": 46,
      "code": "PS",
      "name": {"en": "Ukraine International Airlines", "ar": "الخطوط الجوية الأوكرانية الدولية"},
      "country_code": "ua",
      "image": "ps",
      "note": null,
    },
    {
      "id": 47,
      "code": "PQ",
      "name": {"en": "SkyUp Airlines", "ar": "سكاي أب إيرلاينز"},
      "country_code": "ua",
      "image": "pq",
      "note": null,
    },
    {
      "id": 48,
      "code": "J2",
      "name": {"en": "Azerbaijan Airlines", "ar": "الخطوط الجوية الأذربيجانية"},
      "country_code": "az",
      "image": "j2",
      "note": null,
    },
    {
      "id": 49,
      "code": "A9",
      "name": {"en": "Georgian Airways", "ar": "الخطوط الجوية الجورجية"},
      "country_code": "ge",
      "image": "a9",
      "note": null,
    },
    {
      "id": 50,
      "code": "4O",
      "name": {"en": "Air Montenegro", "ar": "طيران الجبل الأسود"},
      "country_code": "me",
      "image": "4o",
      "note": null,
    },
    {
      "id": 51,
      "code": "JU",
      "name": {"en": "Air Serbia", "ar": "طيران صربيا"},
      "country_code": "rs",
      "image": "ju",
      "note": null,
    },
    {
      "id": 52,
      "code": "TK",
      "name": {"en": "Turkish Airlines", "ar": "الخطوط الجوية التركية"},
      "country_code": "tr",
      "image": "tk",
      "note": null,
    },
    {
      "id": 53,
      "code": "PC",
      "name": {"en": "Pegasus Airlines", "ar": "طيران بيجاسوس"},
      "country_code": "tr",
      "image": "pc",
      "note": null,
    },
    {
      "id": 54,
      "code": "XQ",
      "name": {"en": "SunExpress", "ar": "صن إكسبريس"},
      "country_code": "tr",
      "image": "xq",
      "note": null,
    },
    {
      "id": 55,
      "code": "LO",
      "name": {"en": "LOT Polish Airlines", "ar": "الخطوط الجوية البولندية لوت"},
      "country_code": "pl",
      "image": "lo",
      "note": null,
    },
    {
      "id": 56,
      "code": "LH",
      "name": {"en": "Lufthansa", "ar": "لوفتهانزا"},
      "country_code": "de",
      "image": "lh",
      "note": null,
    },
    {
      "id": 57,
      "code": "LX",
      "name": {"en": "SWISS", "ar": "سويس الدولية للطيران"},
      "country_code": "ch",
      "image": "lx",
      "note": null,
    },
    {
      "id": 58,
      "code": "OS",
      "name": {"en": "Austrian Airlines", "ar": "الخطوط الجوية النمساوية"},
      "country_code": "at",
      "image": "os",
      "note": null,
    },
    {
      "id": 59,
      "code": "SN",
      "name": {"en": "Brussels Airlines", "ar": "خطوط بروكسل الجوية"},
      "country_code": "be",
      "image": "sn",
      "note": null,
    },
    {
      "id": 60,
      "code": "KL",
      "name": {"en": "KLM Royal Dutch Airlines", "ar": "الخطوط الملكية الهولندية كي إل إم"},
      "country_code": "nl",
      "image": "kl",
      "note": null,
    },
    {
      "id": 61,
      "code": "AF",
      "name": {"en": "Air France", "ar": "الخطوط الجوية الفرنسية"},
      "country_code": "fr",
      "image": "af",
      "note": null,
    },
    {
      "id": 62,
      "code": "BA",
      "name": {"en": "British Airways", "ar": "الخطوط الجوية البريطانية"},
      "country_code": "gb",
      "image": "ba",
      "note": null,
    },
    {
      "id": 63,
      "code": "U2",
      "name": {"en": "easyJet", "ar": "إيزي جِت"},
      "country_code": "gb",
      "image": "u2",
      "note": null,
    },
    {
      "id": 64,
      "code": "LS",
      "name": {"en": "Jet2.com", "ar": "جيت2 دوت كوم"},
      "country_code": "gb",
      "image": "ls",
      "note": null,
    },
    {
      "id": 65,
      "code": "VS",
      "name": {"en": "Virgin Atlantic", "ar": "فيرجن أتلانتيك"},
      "country_code": "gb",
      "image": "vs",
      "note": null,
    },
    {
      "id": 66,
      "code": "FR",
      "name": {"en": "Ryanair", "ar": "ريان إير"},
      "country_code": "ie",
      "image": "fr",
      "note": null,
    },
    {
      "id": 67,
      "code": "EI",
      "name": {"en": "Aer Lingus", "ar": "إير لينغس"},
      "country_code": "ie",
      "image": "ei",
      "note": null,
    },
    {
      "id": 68,
      "code": "IB",
      "name": {"en": "Iberia", "ar": "إيبيريا"},
      "country_code": "es",
      "image": "ib",
      "note": null,
    },
    {
      "id": 69,
      "code": "UX",
      "name": {"en": "Air Europa", "ar": "إير يوروبا"},
      "country_code": "es",
      "image": "ux",
      "note": null,
    },
    {
      "id": 70,
      "code": "VY",
      "name": {"en": "Vueling", "ar": "فويلينغ"},
      "country_code": "es",
      "image": "vy",
      "note": null,
    },
    {
      "id": 71,
      "code": "HV",
      "name": {"en": "Transavia", "ar": "ترانسافيا"},
      "country_code": "nl",
      "image": "hv",
      "note": null,
    },
    {
      "id": 72,
      "code": "TO",
      "name": {"en": "Transavia France", "ar": "ترانسافيا فرنسا"},
      "country_code": "fr",
      "image": "to",
      "note": null,
    },
    {
      "id": 73,
      "code": "EW",
      "name": {"en": "Eurowings", "ar": "يورو وينغز"},
      "country_code": "de",
      "image": "ew",
      "note": null,
    },
    {
      "id": 74,
      "code": "DE",
      "name": {"en": "Condor", "ar": "كوندور"},
      "country_code": "de",
      "image": "de",
      "note": null,
    },
    {
      "id": 75,
      "code": "4Y",
      "name": {"en": "Discover Airlines", "ar": "ديسكاڤر إيرلاينز"},
      "country_code": "de",
      "image": "4y",
      "note": null,
    },
    {
      "id": 76,
      "code": "EN",
      "name": {"en": "Air Dolomiti", "ar": "إير دولوميتي"},
      "country_code": "it",
      "image": "en",
      "note": null,
    },
    {
      "id": 77,
      "code": "AZ",
      "name": {"en": "ITA Airways", "ar": "إيتا إيرويز"},
      "country_code": "it",
      "image": "az",
      "note": null,
    },
    {
      "id": 78,
      "code": "A3",
      "name": {"en": "Aegean Airlines", "ar": "طيران إيجه"},
      "country_code": "gr",
      "image": "a3",
      "note": null,
    },
    {
      "id": 79,
      "code": "OA",
      "name": {"en": "Olympic Air", "ar": "أولمبيك إير"},
      "country_code": "gr",
      "image": "oa",
      "note": null,
    },
    {
      "id": 80,
      "code": "BT",
      "name": {"en": "airBaltic", "ar": "إير بالتك"},
      "country_code": "lv",
      "image": "bt",
      "note": null,
    },
    {
      "id": 81,
      "code": "OK",
      "name": {"en": "Czech Airlines", "ar": "الخطوط الجوية التشيكية"},
      "country_code": "cz",
      "image": "ok",
      "note": null,
    },
    {
      "id": 82,
      "code": "OU",
      "name": {"en": "Croatia Airlines", "ar": "الخطوط الجوية الكرواتية"},
      "country_code": "hr",
      "image": "ou",
      "note": null,
    },
    {
      "id": 83,
      "code": "RO",
      "name": {"en": "TAROM", "ar": "تاروم"},
      "country_code": "ro",
      "image": "ro",
      "note": null,
    },
    {
      "id": 84,
      "code": "FB",
      "name": {"en": "Bulgaria Air", "ar": "طيران بلغاريا"},
      "country_code": "bg",
      "image": "fb",
      "note": null,
    },
    {
      "id": 85,
      "code": "SK",
      "name": {"en": "SAS Scandinavian Airlines", "ar": "ساس الخطوط الإسكندنافية"},
      "country_code": "se",
      "image": "sk",
      "note": null,
    },
    {
      "id": 86,
      "code": "DY",
      "name": {"en": "Norwegian Air Shuttle", "ar": "الخطوط الجوية النرويجية"},
      "country_code": "no",
      "image": "dy",
      "note": null,
    },
    {
      "id": 87,
      "code": "W6",
      "name": {"en": "Wizz Air", "ar": "ويز إير"},
      "country_code": "hu",
      "image": "w6",
      "note": null,
    },
    {
      "id": 88,
      "code": "W9",
      "name": {"en": "Wizz Air UK", "ar": "ويز إير المملكة المتحدة"},
      "country_code": "gb",
      "image": "w9",
      "note": null,
    },
    {
      "id": 89,
      "code": "5W",
      "name": {"en": "Wizz Air Abu Dhabi", "ar": "ويز إير أبوظبي"},
      "country_code": "ae",
      "image": "5w",
      "note": null,
    },
    {
      "id": 90,
      "code": "NH",
      "name": {"en": "All Nippon Airways", "ar": "خطوط كل نيبون الجوية"},
      "country_code": "jp",
      "image": "nh",
      "note": null,
    },
    {
      "id": 91,
      "code": "JL",
      "name": {"en": "Japan Airlines", "ar": "الخطوط الجوية اليابانية"},
      "country_code": "jp",
      "image": "jl",
      "note": null,
    },
    {
      "id": 92,
      "code": "MM",
      "name": {"en": "Peach Aviation", "ar": "بيتش أفيايشن"},
      "country_code": "jp",
      "image": "mm",
      "note": null,
    },
    {
      "id": 93,
      "code": "GK",
      "name": {"en": "Jetstar Japan", "ar": "جيت ستار اليابان"},
      "country_code": "jp",
      "image": "gk",
      "note": null,
    },
    {
      "id": 94,
      "code": "BC",
      "name": {"en": "Skymark Airlines", "ar": "سكاي مارك إيرلاينز"},
      "country_code": "jp",
      "image": "bc",
      "note": null,
    },
    {
      "id": 95,
      "code": "KE",
      "name": {"en": "Korean Air", "ar": "الخطوط الجوية الكورية"},
      "country_code": "kr",
      "image": "ke",
      "note": null,
    },
    {
      "id": 96,
      "code": "OZ",
      "name": {"en": "Asiana Airlines", "ar": "الخطوط الجوية آسيانا"},
      "country_code": "kr",
      "image": "oz",
      "note": null,
    },
    {
      "id": 97,
      "code": "7C",
      "name": {"en": "Jeju Air", "ar": "جيجو إير"},
      "country_code": "kr",
      "image": "7c",
      "note": null,
    },
    {
      "id": 98,
      "code": "LJ",
      "name": {"en": "Jin Air", "ar": "جين إير"},
      "country_code": "kr",
      "image": "lj",
      "note": null,
    },
    {
      "id": 99,
      "code": "TW",
      "name": {"en": "T'way Air", "ar": "تيواي إير"},
      "country_code": "kr",
      "image": "tw",
      "note": null,
    },
    {
      "id": 100,
      "code": "VN",
      "name": {"en": "Vietnam Airlines", "ar": "الخطوط الجوية الفيتنامية"},
      "country_code": "vn",
      "image": "vn",
      "note": null,
    },
    {
      "id": 101,
      "code": "VJ",
      "name": {"en": "VietJet Air", "ar": "فييت جيت إير"},
      "country_code": "vn",
      "image": "vj",
      "note": null,
    },
    {
      "id": 102,
      "code": "QH",
      "name": {"en": "Bamboo Airways", "ar": "بامبو إيرويز"},
      "country_code": "vn",
      "image": "qh",
      "note": null,
    },
    {
      "id": 103,
      "code": "TG",
      "name": {"en": "Thai Airways", "ar": "الخطوط الجوية التايلاندية"},
      "country_code": "th",
      "image": "tg",
      "note": null,
    },
    {
      "id": 104,
      "code": "FD",
      "name": {"en": "Thai AirAsia", "ar": "طيران تاي إيرآسيا"},
      "country_code": "th",
      "image": "fd",
      "note": null,
    },
    {
      "id": 105,
      "code": "SL",
      "name": {"en": "Thai Lion Air", "ar": "تاي ليون إير"},
      "country_code": "th",
      "image": "sl",
      "note": null,
    },
    {
      "id": 106,
      "code": "PG",
      "name": {"en": "Bangkok Airways", "ar": "بانكوك إيروايز"},
      "country_code": "th",
      "image": "pg",
      "note": null,
    },
    {
      "id": 107,
      "code": "GA",
      "name": {"en": "Garuda Indonesia", "ar": "غارودا إندونيسيا"},
      "country_code": "id",
      "image": "ga",
      "note": null,
    },
    {
      "id": 108,
      "code": "JT",
      "name": {"en": "Lion Air", "ar": "لايون إير"},
      "country_code": "id",
      "image": "jt",
      "note": null,
    },
    {
      "id": 109,
      "code": "ID",
      "name": {"en": "Batik Air (Indonesia)", "ar": "باتيك إير (إندونيسيا)"},
      "country_code": "id",
      "image": "id",
      "note": null,
    },
    {
      "id": 110,
      "code": "QZ",
      "name": {"en": "Indonesia AirAsia", "ar": "إندونيسيا إيرآسيا"},
      "country_code": "id",
      "image": "qz",
      "note": null,
    },
    {
      "id": 111,
      "code": "MH",
      "name": {"en": "Malaysia Airlines", "ar": "الخطوط الجوية الماليزية"},
      "country_code": "my",
      "image": "mh",
      "note": null,
    },
    {
      "id": 112,
      "code": "AK",
      "name": {"en": "AirAsia", "ar": "إيرآسيا"},
      "country_code": "my",
      "image": "ak",
      "note": null,
    },
    {
      "id": 113,
      "code": "OD",
      "name": {"en": "Batik Air Malaysia", "ar": "باتيك إير ماليزيا"},
      "country_code": "my",
      "image": "od",
      "note": null,
    },
    {
      "id": 114,
      "code": "SQ",
      "name": {"en": "Singapore Airlines", "ar": "الخطوط الجوية السنغافورية"},
      "country_code": "sg",
      "image": "sq",
      "note": null,
    },
    {
      "id": 115,
      "code": "TR",
      "name": {"en": "Scoot", "ar": "سكوت"},
      "country_code": "sg",
      "image": "tr",
      "note": null,
    },
    {
      "id": 116,
      "code": "BR",
      "name": {"en": "EVA Air", "ar": "إيفا إير"},
      "country_code": "tw",
      "image": "br",
      "note": null,
    },
    {
      "id": 117,
      "code": "CI",
      "name": {"en": "China Airlines", "ar": "الخطوط الجوية الصينية"},
      "country_code": "tw",
      "image": "ci",
      "note": null,
    },
    {
      "id": 118,
      "code": "AE",
      "name": {"en": "Mandarin Airlines", "ar": "ماندارين إيرلاينز"},
      "country_code": "tw",
      "image": "ae",
      "note": null,
    },
    {
      "id": 119,
      "code": "CX",
      "name": {"en": "Cathay Pacific", "ar": "كاثي باسيفيك"},
      "country_code": "hk",
      "image": "cx",
      "note": null,
    },
    {
      "id": 120,
      "code": "HX",
      "name": {"en": "Hong Kong Airlines", "ar": "خطوط هونغ كونغ الجوية"},
      "country_code": "hk",
      "image": "hx",
      "note": null,
    },
    {
      "id": 121,
      "code": "UO",
      "name": {"en": "HK Express", "ar": "إتش كيه إكسبريس"},
      "country_code": "hk",
      "image": "uo",
      "note": null,
    },
    {
      "id": 122,
      "code": "CA",
      "name": {"en": "Air China", "ar": "إير تشاينا"},
      "country_code": "cn",
      "image": "ca",
      "note": null,
    },
    {
      "id": 123,
      "code": "MU",
      "name": {"en": "China Eastern Airlines", "ar": "تشاينا إيسترن إيرلاينز"},
      "country_code": "cn",
      "image": "mu",
      "note": null,
    },
    {
      "id": 124,
      "code": "CZ",
      "name": {"en": "China Southern Airlines", "ar": "تشاينا ساوثرن إيرلاينز"},
      "country_code": "cn",
      "image": "cz",
      "note": null,
    },
    {
      "id": 125,
      "code": "HU",
      "name": {"en": "Hainan Airlines", "ar": "هاينان إيرلاينز"},
      "country_code": "cn",
      "image": "hu",
      "note": null,
    },
    {
      "id": 126,
      "code": "ZH",
      "name": {"en": "Shenzhen Airlines", "ar": "شنجن إيرلاينز"},
      "country_code": "cn",
      "image": "zh",
      "note": null,
    },
    {
      "id": 127,
      "code": "FM",
      "name": {"en": "Shanghai Airlines", "ar": "شنغهاي إيرلاينز"},
      "country_code": "cn",
      "image": "fm",
      "note": null,
    },
    {
      "id": 128,
      "code": "MF",
      "name": {"en": "XiamenAir", "ar": "شيامن إير"},
      "country_code": "cn",
      "image": "mf",
      "note": null,
    },
    {
      "id": 129,
      "code": "3U",
      "name": {"en": "Sichuan Airlines", "ar": "سيتشوان إيرلاينز"},
      "country_code": "cn",
      "image": "3u",
      "note": null,
    },
    {
      "id": 130,
      "code": "SC",
      "name": {"en": "Shandong Airlines", "ar": "شاندونغ إيرلاينز"},
      "country_code": "cn",
      "image": "sc",
      "note": null,
    },
    {
      "id": 131,
      "code": "HO",
      "name": {"en": "Juneyao Air", "ar": "جونيياو إير"},
      "country_code": "cn",
      "image": "ho",
      "note": null,
    },
    {
      "id": 132,
      "code": "9C",
      "name": {"en": "Spring Airlines", "ar": "سبرينغ إيرلاينز"},
      "country_code": "cn",
      "image": "9c",
      "note": null,
    },
    {
      "id": 133,
      "code": "PN",
      "name": {"en": "West Air (China)", "ar": "وست إير (الصين)"},
      "country_code": "cn",
      "image": "pn",
      "note": null,
    },
    {
      "id": 134,
      "code": "G5",
      "name": {"en": "China Express Airlines", "ar": "تشاينا إكسبريس إيرلاينز"},
      "country_code": "cn",
      "image": "g5",
      "note": null,
    },
    {
      "id": 135,
      "code": "Y8",
      "name": {"en": "Suparna Airlines", "ar": "سوبارنا إيرلاينز"},
      "country_code": "cn",
      "image": "y8",
      "note": null,
    },
    {
      "id": 136,
      "code": "OQ",
      "name": {"en": "Chongqing Airlines", "ar": "تشونغتشينغ إيرلاينز"},
      "country_code": "cn",
      "image": "oq",
      "note": null,
    },
    {
      "id": 137,
      "code": "NS",
      "name": {"en": "Hebei Airlines", "ar": "خهبي إيرلاينز"},
      "country_code": "cn",
      "image": "ns",
      "note": null,
    },
    {
      "id": 138,
      "code": "GX",
      "name": {"en": "Guangxi Beibu Gulf Airlines", "ar": "غوانغشي بيبو غلف إيرلاينز"},
      "country_code": "cn",
      "image": "gx",
      "note": null,
    },
    {
      "id": 139,
      "code": "AI",
      "name": {"en": "Air India", "ar": "إير إنديا"},
      "country_code": "in",
      "image": "ai",
      "note": null,
    },
    {
      "id": 140,
      "code": "IX",
      "name": {"en": "Air India Express", "ar": "إير إنديا إكسبريس"},
      "country_code": "in",
      "image": "ix",
      "note": null,
    },
    {
      "id": 141,
      "code": "UK",
      "name": {"en": "Vistara", "ar": "فيستارا"},
      "country_code": "in",
      "image": "uk",
      "note": null,
    },
    {
      "id": 142,
      "code": "6E",
      "name": {"en": "IndiGo", "ar": "إنديغو"},
      "country_code": "in",
      "image": "6e",
      "note": null,
    },
    {
      "id": 143,
      "code": "SG",
      "name": {"en": "SpiceJet", "ar": "سبايس جِت"},
      "country_code": "in",
      "image": "sg",
      "note": null,
    },
    {
      "id": 144,
      "code": "BG",
      "name": {"en": "Biman Bangladesh Airlines", "ar": "بيمان بنغلادش إيرلاينز"},
      "country_code": "bd",
      "image": "bg",
      "note": null,
    },
    {
      "id": 145,
      "code": "BS",
      "name": {"en": "US-Bangla Airlines", "ar": "يو إس-بنغلا إيرلاينز"},
      "country_code": "bd",
      "image": "bs",
      "note": null,
    },
    {
      "id": 146,
      "code": "UL",
      "name": {"en": "SriLankan Airlines", "ar": "الخطوط الجوية السريلانكية"},
      "country_code": "lk",
      "image": "ul",
      "note": null,
    },
    {
      "id": 147,
      "code": "RA",
      "name": {"en": "Nepal Airlines", "ar": "الخطوط الجوية النيبالية"},
      "country_code": "np",
      "image": "ra",
      "note": null,
    },
    {
      "id": 148,
      "code": "QF",
      "name": {"en": "Qantas", "ar": "كانتاس"},
      "country_code": "au",
      "image": "qf",
      "note": null,
    },
    {
      "id": 149,
      "code": "JQ",
      "name": {"en": "Jetstar Airways", "ar": "جيت ستار إيروايز"},
      "country_code": "au",
      "image": "jq",
      "note": null,
    },
    {
      "id": 150,
      "code": "VA",
      "name": {"en": "Virgin Australia", "ar": "فيرجن أستراليا"},
      "country_code": "au",
      "image": "va",
      "note": null,
    },
    {
      "id": 151,
      "code": "NZ",
      "name": {"en": "Air New Zealand", "ar": "إير نيوزيلندا"},
      "country_code": "nz",
      "image": "nz",
      "note": null,
    },
    {
      "id": 152,
      "code": "FJ",
      "name": {"en": "Fiji Airways", "ar": "فيجي إيروايز"},
      "country_code": "fj",
      "image": "fj",
      "note": null,
    },
    {
      "id": 153,
      "code": "PX",
      "name": {"en": "Air Niugini", "ar": "إير نيوغيني"},
      "country_code": "pg",
      "image": "px",
      "note": null,
    },
    {
      "id": 154,
      "code": "NF",
      "name": {"en": "Air Vanuatu", "ar": "إير فانواتو"},
      "country_code": "vu",
      "image": "nf",
      "note": null,
    },
    {
      "id": 155,
      "code": "TN",
      "name": {"en": "Air Tahiti Nui", "ar": "إير تاهيتي نوي"},
      "country_code": "pf",
      "image": "tn",
      "note": null,
    },
    {
      "id": 156,
      "code": "AA",
      "name": {"en": "American Airlines", "ar": "الخطوط الجوية الأمريكية"},
      "country_code": "us",
      "image": "aa",
      "note": null,
    },
    {
      "id": 157,
      "code": "UA",
      "name": {"en": "United Airlines", "ar": "يونايتد إيرلاينز"},
      "country_code": "us",
      "image": "ua",
      "note": null,
    },
    {
      "id": 158,
      "code": "DL",
      "name": {"en": "Delta Air Lines", "ar": "دلتا إيرلاينز"},
      "country_code": "us",
      "image": "dl",
      "note": null,
    },
    {
      "id": 159,
      "code": "WN",
      "name": {"en": "Southwest Airlines", "ar": "ساوث ويست إيرلاينز"},
      "country_code": "us",
      "image": "wn",
      "note": null,
    },
    {
      "id": 160,
      "code": "AS",
      "name": {"en": "Alaska Airlines", "ar": "ألاسكا إيرلاينز"},
      "country_code": "us",
      "image": "as",
      "note": null,
    },
    {
      "id": 161,
      "code": "B6",
      "name": {"en": "JetBlue", "ar": "جيت بلو"},
      "country_code": "us",
      "image": "b6",
      "note": null,
    },
    {
      "id": 162,
      "code": "F9",
      "name": {"en": "Frontier Airlines", "ar": "فرونتير إيرلاينز"},
      "country_code": "us",
      "image": "f9",
      "note": null,
    },
    {
      "id": 163,
      "code": "NK",
      "name": {"en": "Spirit Airlines", "ar": "سبيريت إيرلاينز"},
      "country_code": "us",
      "image": "nk",
      "note": null,
    },
    {
      "id": 164,
      "code": "HA",
      "name": {"en": "Hawaiian Airlines", "ar": "هاوايَن إيرلاينز"},
      "country_code": "us",
      "image": "ha",
      "note": null,
    },
    {
      "id": 165,
      "code": "G4",
      "name": {"en": "Allegiant Air", "ar": "أليجيانت إير"},
      "country_code": "us",
      "image": "g4",
      "note": null,
    },
    {
      "id": 166,
      "code": "SY",
      "name": {"en": "Sun Country Airlines", "ar": "صن كنتري إيرلاينز"},
      "country_code": "us",
      "image": "sy",
      "note": null,
    },
    {
      "id": 167,
      "code": "AC",
      "name": {"en": "Air Canada", "ar": "إير كندا"},
      "country_code": "ca",
      "image": "ac",
      "note": null,
    },
    {
      "id": 168,
      "code": "WS",
      "name": {"en": "WestJet", "ar": "وستجت"},
      "country_code": "ca",
      "image": "ws",
      "note": null,
    },
    {
      "id": 169,
      "code": "PD",
      "name": {"en": "Porter Airlines", "ar": "بوتر إيرلاينز"},
      "country_code": "ca",
      "image": "pd",
      "note": null,
    },
    {
      "id": 170,
      "code": "TS",
      "name": {"en": "Air Transat", "ar": "إير ترانسات"},
      "country_code": "ca",
      "image": "ts",
      "note": null,
    },
    {
      "id": 171,
      "code": "F8",
      "name": {"en": "Flair Airlines", "ar": "فلير إيرلاينز"},
      "country_code": "ca",
      "image": "f8",
      "note": null,
    },
    {
      "id": 172,
      "code": "AM",
      "name": {"en": "AeroMéxico", "ar": "أيرو ميكسيكو"},
      "country_code": "mx",
      "image": "am",
      "note": null,
    },
    {
      "id": 173,
      "code": "Y4",
      "name": {"en": "Volaris", "ar": "فولاريس"},
      "country_code": "mx",
      "image": "y4",
      "note": null,
    },
    {
      "id": 174,
      "code": "VB",
      "name": {"en": "Viva Aerobus", "ar": "فيفا إيروباص"},
      "country_code": "mx",
      "image": "vb",
      "note": null,
    },
    {
      "id": 175,
      "code": "AV",
      "name": {"en": "Avianca", "ar": "أفيانكا"},
      "country_code": "co",
      "image": "av",
      "note": null,
    },
    {
      "id": 176,
      "code": "CM",
      "name": {"en": "Copa Airlines", "ar": "كوپا إيرلاينز"},
      "country_code": "pa",
      "image": "cm",
      "note": null,
    },
    {
      "id": 177,
      "code": "LA",
      "name": {"en": "LATAM Airlines", "ar": "لاتام إيرلاينز"},
      "country_code": "cl",
      "image": "la",
      "note": null,
    },
    {
      "id": 178,
      "code": "AR",
      "name": {"en": "Aerolíneas Argentinas", "ar": "أيروليناس أرجنتيناس"},
      "country_code": "ar",
      "image": "ar",
      "note": null,
    },
    {
      "id": 179,
      "code": "FO",
      "name": {"en": "Flybondi", "ar": "فلاي بوندي"},
      "country_code": "ar",
      "image": "fo",
      "note": null,
    },
    {
      "id": 180,
      "code": "G3",
      "name": {"en": "GOL Linhas Aéreas", "ar": "غول لينهاس آيَرِس"},
      "country_code": "br",
      "image": "g3",
      "note": null,
    },
    {
      "id": 181,
      "code": "AD",
      "name": {"en": "Azul Brazilian Airlines", "ar": "أزول البرازيلية"},
      "country_code": "br",
      "image": "ad",
      "note": null,
    },
    {
      "id": 182,
      "code": "H2",
      "name": {"en": "Sky Airline", "ar": "سكاي إيرلاين"},
      "country_code": "cl",
      "image": "h2",
      "note": null,
    },
    {
      "id": 183,
      "code": "TA",
      "name": {"en": "Avianca El Salvador", "ar": "أفيانكا السلفادور"},
      "country_code": "sv",
      "image": "ta",
      "note": null,
    },
    {
      "id": 184,
      "code": "BW",
      "name": {"en": "Caribbean Airlines", "ar": "كاريبيان إيرلاينز"},
      "country_code": "tt",
      "image": "bw",
      "note": null,
    },
    {
      "id": 185,
      "code": "PY",
      "name": {"en": "Surinam Airways", "ar": "سورينام إيروايز"},
      "country_code": "sr",
      "image": "py",
      "note": null,
    },
    {
      "id": 186,
      "code": "OM",
      "name": {"en": "MIAT Mongolian Airlines", "ar": "خطوط مييات المنغولية"},
      "country_code": "mn",
      "image": "om",
      "note": null,
    },
    {
      "id": 187,
      "code": "BI",
      "name": {"en": "Royal Brunei Airlines", "ar": "الخطوط الجوية الملكية البروناوية"},
      "country_code": "bn",
      "image": "bi",
      "note": null,
    },
    {
      "id": 188,
      "code": "PR",
      "name": {"en": "Philippine Airlines", "ar": "الخطوط الجوية الفلبينية"},
      "country_code": "ph",
      "image": "pr",
      "note": null,
    },
    {
      "id": 189,
      "code": "5J",
      "name": {"en": "Cebu Pacific Air", "ar": "سيبو باسيفيك"},
      "country_code": "ph",
      "image": "5j",
      "note": null,
    },
    {
      "id": 190,
      "code": "DG",
      "name": {"en": "Cebgo", "ar": "سيبغو"},
      "country_code": "ph",
      "image": "dg",
      "note": null,
    },
  ];

  Future<List<Map<String, dynamic>>> search(String query) async {
    await Future.delayed(const Duration(milliseconds: 500)); // تأخير بسيط
    final q = query.trim().toLowerCase();
    // if (q.isEmpty) return [];
    // البحث بالرمز او الاسم او الوصف
    final res = data.where((element) {
      final e = AirlineModel.fromJson(element);
      return e.code.toLowerCase().contains(q) ||
          e.name['en'].toString().toLowerCase().contains(q) ||
          e.name['ar'].toString().toLowerCase().contains(q) ||
          e.countryCode.toLowerCase().contains(q) ||
          (e.note ?? '').toLowerCase().contains(q);
    }).toList();
    // حد اقصى (لانقاص الحمل)
    return res.take(1000).toList();
  }
}
